# Generated by Django 2.1 on 2018-08-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180815_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='roll',
        ),
        migrations.DeleteModel(
            name='ReturnBook',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
