# Generated by Django 2.1 on 2018-08-15 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_auto_20180815_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('remaining', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=10)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Book')),
            ],
        ),
        migrations.CreateModel(
            name='rbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('depertment_name', models.CharField(max_length=30)),
                ('roll_number', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
