# Generated by Django 2.1 on 2018-08-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180815_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rbook',
            new_name='Return',
        ),
    ]
